apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (include "notes-app.fullname" .) .Values.resourceName }}
  namespace: {{ .Values.notesApp.namespace }}
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
data:
  DB_TYPE: {{ .Values.notesApp.config.DB_TYPE | quote }}
  DB_SERVICE: {{ .Values.notesApp.config.DB_SERVICE | quote }}
  DB_NAME: {{ .Values.notesApp.config.DB_NAME | quote }}
  DB_USER: {{ .Values.notesApp.config.DB_USER | quote }}
  DB_PORT: {{ .Values.notesApp.config.DB_PORT | quote }}
  MAXIMUM_NOTE_LENGTH: {{ .Values.notesApp.config.MAXIMUM_NOTE_LENGTH | quote }}
  FLASK_DEBUG: {{ .Values.flaskDebug | quote }}
