apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "notes-app.fullname" .) .Values.resourceName }}
  namespace: {{ .Values.notesApp.namespace }}
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
type: Opaque
data:
  FLASK_SECRET_KEY: {{ .Values.notesApp.secrets.FLASK_SECRET_KEY | quote }}
  DB_PASSWORD: {{ .Values.notesApp.secrets.DB_PASSWORD | quote }}
